### ISSUE TITLE
No Login Required After Logging Out

### ISSUE THREAD

**Issue by jackiehdinh** [SCCapstone/DKMS#336]
After you log out, when you try to log in again, it doesn't require you to type in login information. 

https://user-images.githubusercontent.com/89161210/230754840-eefd7ece-5e7e-46b6-83d5-41ae25a4bcb6.mp4

Steps to Reproduce
- Login
- Logout
- Login Again

**Comment by cravend** [comment]
Unfortunately, logging out of Spotify and logging out of DKMS are completely separate (we can't access the Spotify website's session data/cookies). This means that clicking the logout button in the sidebar won't log you out of open.spotify.com, but it also means that when you re-login, Spotify just automatically accepts our request (since you previously granted DKMS access to your account).

If you want to switch between the free and premium accounts, I'd recommend going directly to open.spotify.com and logging out there before clicking logout in our app.
